meta_title: "Sweet Joy"
meta_description: "Find the best bakers"
meta_image: "bolo-colorido.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@lewagonbrussels" # indispensable pour les Twitter Cards
